build:
	g++ main.cc -c #create from the listed files an object
	g++ main.o -o main #create from the main.o data an executable named as main

execute:
	./main #execute main executable

clean:
	rm -f *.o	#	Clean everything with an ending .object
	rm -f main #	Clean the main executable
